[2024-05-12T11:47:39.648+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T11:47:39.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.store_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-05-12T11:47:39.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.store_data scheduled__2024-04-23T00:00:00+00:00 [queued]>
[2024-05-12T11:47:39.692+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-12T11:47:39.719+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_data> on 2024-04-23 00:00:00+00:00
[2024-05-12T11:47:39.727+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'store_data', 'scheduled__2024-04-23T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/script.py', '--cfg-path', '/tmp/tmpcfw4cqne']
[2024-05-12T11:47:39.728+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask store_data
[2024-05-12T11:47:39.731+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=440) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T11:47:39.731+0000] {standard_task_runner.py:63} INFO - Started process 453 to run task
[2024-05-12T11:47:39.790+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.store_data scheduled__2024-04-23T00:00:00+00:00 [running]> on host 06d3d031dcd2
[2024-05-12T11:47:39.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T00:00:00+00:00'
[2024-05-12T11:47:39.890+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T11:47:39.900+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T11:47:39.901+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script.py", line 49, in store_data
    file = drive.CreateFile({'title': os.path.basename(file_path), 'parents': [{'id': 'u/1/folders/1O7Xmsv_6Qaq4eBtRR2SKsZyEIcYQ-7sy'}]})
           ^^^^^
NameError: name 'drive' is not defined
[2024-05-12T11:47:39.912+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=my_dag, task_id=store_data, run_id=scheduled__2024-04-23T00:00:00+00:00, execution_date=20240423T000000, start_date=20240512T114739, end_date=20240512T114739
[2024-05-12T11:47:39.937+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task store_data (name 'drive' is not defined; 453)
[2024-05-12T11:47:39.945+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T11:47:39.970+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T11:47:39.983+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
